[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "battery-xps-analysis"
version = "1.4.4"
description = "This package provides tools for X-ray Photoelectron Spectroscopy (XPS) analysis of battery materials."
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "nb-clean>=4.0.1",
    "numpy>=2.3.0",
    "pre-commit>=4.2.0",
]

[tool.setuptools.packages.find]
# This ensures that xps_analysis is found as a package
include = ["xps_analysis*"]
